//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_Resource_LoadResourceStatusWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(GameFramework.Resource.LoadResourceStatus));
		L.RegVar("Ok", get_Ok, null);
		L.RegVar("NotReady", get_NotReady, null);
		L.RegVar("NotExist", get_NotExist, null);
		L.RegVar("DependencyError", get_DependencyError, null);
		L.RegVar("TypeError", get_TypeError, null);
		L.RegVar("ChildAssetError", get_ChildAssetError, null);
		L.RegVar("SceneAssetError", get_SceneAssetError, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Ok(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.Ok);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NotReady(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.NotReady);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NotExist(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.NotExist);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DependencyError(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.DependencyError);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TypeError(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.TypeError);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ChildAssetError(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.ChildAssetError);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SceneAssetError(IntPtr L)
	{
		ToLua.Push(L, GameFramework.Resource.LoadResourceStatus.SceneAssetError);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		GameFramework.Resource.LoadResourceStatus o = (GameFramework.Resource.LoadResourceStatus)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

