//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class StarForce_GameEntryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(StarForce.GameEntry), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Base", get_Base, null);
		L.RegVar("ConfigCustom", get_ConfigCustom, null);
		L.RegVar("Config", get_Config, null);
		L.RegVar("DataNode", get_DataNode, null);
		L.RegVar("DataTable", get_DataTable, null);
		L.RegVar("Debugger", get_Debugger, null);
		L.RegVar("Download", get_Download, null);
		L.RegVar("Entity", get_Entity, null);
		L.RegVar("Event", get_Event, null);
		L.RegVar("Fsm", get_Fsm, null);
		L.RegVar("Localization", get_Localization, null);
		L.RegVar("Network", get_Network, null);
		L.RegVar("ObjectPool", get_ObjectPool, null);
		L.RegVar("Procedure", get_Procedure, null);
		L.RegVar("Resource", get_Resource, null);
		L.RegVar("Scene", get_Scene, null);
		L.RegVar("Setting", get_Setting, null);
		L.RegVar("Sound", get_Sound, null);
		L.RegVar("UI", get_UI, null);
		L.RegVar("WebRequest", get_WebRequest, null);
		L.RegVar("BuiltinData", get_BuiltinData, null);
		L.RegVar("HPBar", get_HPBar, null);
		L.RegVar("LuaComponent", get_LuaComponent, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Base(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Base);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ConfigCustom(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.ConfigCustom);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Config(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Config);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DataNode(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.DataNode);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DataTable(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.DataTable);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Debugger(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Debugger);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Download(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Download);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Entity(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Entity);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Event(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Event);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fsm(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Fsm);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Localization(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Localization);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Network(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Network);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ObjectPool(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.ObjectPool);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Procedure(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Procedure);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Resource(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Resource);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scene(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Scene);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Setting(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Setting);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sound(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.Sound);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UI(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.UI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WebRequest(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.WebRequest);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BuiltinData(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.BuiltinData);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HPBar(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.HPBar);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaComponent(IntPtr L)
	{
		try
		{
			ToLua.Push(L, StarForce.GameEntry.LuaComponent);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

