//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityGameFramework_Runtime_Constant_DevicePlatform_DevicePlamformEnumWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum));
		L.RegVar("NULL", get_NULL, null);
		L.RegVar("Windows", get_Windows, null);
		L.RegVar("iOS", get_iOS, null);
		L.RegVar("Android", get_Android, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NULL(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum.NULL);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Windows(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum.Windows);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_iOS(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum.iOS);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Android(IntPtr L)
	{
		ToLua.Push(L, UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum.Android);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum o = (UnityGameFramework.Runtime.Constant.DevicePlatform.DevicePlamformEnum)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

